<?php

declare(strict_types=1);

namespace OCA\BoudicaAi\Service;

use OCP\Mail\IMailer;
use OCP\Mail\IMessage;
use OCP\IConfig;
use Psr\Log\LoggerInterface;

class TranscriptEmailService {
    private IMailer $mailer;
    private LoggerInterface $logger;
    private string $fromAddress;
    private string $fromName;
    private string $instanceLabel;

    public function __construct(
        IMailer $mailer,
        IConfig $config,
        LoggerInterface $logger
    ) {
        $this->mailer = $mailer;
        $this->logger = $logger;

        // Was hardcoded to 'boudica@myboudica.com' / "Nextcloud Instance:
        // boudi.ca" - leftover production branding that showed up verbatim
        // on every deployment regardless of its own actual domain.
        // mail_from_address/mail_domain (Nextcloud core's own outgoing-mail
        // identity) aren't set on this deployment - confirmed live
        // 2026-09-05 (occ config:system:get returns empty for both) - so
        // this derives from overwritehost instead, which setup.sh always
        // sets. Falls back to the old defaults only if that's somehow also
        // unset, rather than producing an invalid from-address.
        $host = (string) $config->getSystemValue('overwritehost', '');
        $hostname = $host !== '' ? preg_replace('/:\d+$/', '', $host) : '';

        $this->fromAddress = $hostname !== '' ? 'boudica@' . $hostname : 'boudica@myboudica.com';
        $this->fromName = 'Boudica';
        $this->instanceLabel = $host !== '' ? $host : 'boudi.ca';
    }

    /**
     * Sends call transcript to participants
     * 
     * @param array $recipients Associative array of email => display_name
     * @param string $callSummary Transcript text or AI-generated summary
     * @param string $roomName The Talk room name
     * @param int $callStartTime Unix timestamp of call start
     * @return bool Success status
     */
    public function sendTranscriptEmail(array $recipients, string $callSummary, string $roomName, int $callStartTime): bool {
        if (empty($recipients)) {
            $this->logger->warning('No recipients to send transcript email');
            return false;
        }

        try {
            $message = $this->mailer->createMessage();
            $message->setFrom([$this->fromAddress => $this->fromName]);
            
            // Build the full recipient list first, then set it once — setTo()
            // REPLACES the whole recipient list on each call, it doesn't add to it.
            // Calling it inside a loop (as before) meant only the last recipient in
            // $recipients actually ended up on the outgoing message; everyone before
            // them was silently overwritten and never received the email.
            $toList = [];
            foreach ($recipients as $email => $displayName) {
                $toList[$email] = $displayName;
            }
            $message->setTo($toList);

            $message->setSubject("Call Transcript: $roomName - " . date('Y-m-d H:i', $callStartTime));

            // Build HTML email
            $callDate = date('l, F j, Y \a\t g:i A', $callStartTime);
            $html = <<<HTML
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>Call Transcript</h2>
    <p><strong>Room:</strong> $roomName</p>
    <p><strong>Date & Time:</strong> $callDate</p>
    <p><strong>Participants:</strong> {COUNT}</p>
    
    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    
    <h3>Transcript</h3>
    <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; white-space: pre-wrap;">
        {TRANSCRIPT}
    </div>
    
    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    
    <p style="font-size: 12px; color: #999;">
        This transcript was automatically generated by Boudica AI.
        <br>Nextcloud Instance: {INSTANCE}
    </p>
</body>
</html>
HTML;

            $html = str_replace('{COUNT}', (string) count($recipients), $html);
            $html = str_replace('{TRANSCRIPT}', htmlspecialchars($callSummary, ENT_QUOTES, 'UTF-8'), $html);
            $html = str_replace('{INSTANCE}', htmlspecialchars($this->instanceLabel, ENT_QUOTES, 'UTF-8'), $html);

            $message->setHtmlBody($html);

            // Also set plain text fallback
            $plainText = "Call Transcript\n\n";
            $plainText .= "Room: $roomName\n";
            $plainText .= "Date & Time: $callDate\n";
            $plainText .= "Participants: " . count($recipients) . "\n\n";
            $plainText .= "Transcript:\n";
            $plainText .= $callSummary;

            $message->setPlainBody($plainText);

            $this->mailer->send($message);

            $this->logger->info('Transcript email sent to ' . count($recipients) . ' recipients');
            return true;

        } catch (\Throwable $e) {
            $this->logger->error('Failed to send transcript email: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Lets other Talk participants know a meeting was added to someone
     * else's calendar on their behalf. NOT a real calendar invite (no
     * .ics attachment, nothing a mail client can Accept/Decline) — see
     * CalendarSuggestionService's docblock for why a proper iTip REQUEST
     * isn't implemented here. Recipients still need to add the event to
     * their own calendar manually if they want it there.
     *
     * @param array $recipients Associative array of email => display_name
     */
    public function sendMeetingInviteNotification(
        array $recipients,
        string $organizerDisplayName,
        string $title,
        int $startTs,
        string $roomName
    ): bool {
        if (empty($recipients)) {
            return false;
        }

        try {
            $message = $this->mailer->createMessage();
            $message->setFrom([$this->fromAddress => $this->fromName]);
            $message->setTo($recipients);
            $message->setSubject("Meeting added: $title");

            $when = date('l, F j, Y \a\t g:i A', $startTs);
            $safeOrganizer = htmlspecialchars($organizerDisplayName, ENT_QUOTES, 'UTF-8');
            $safeTitle = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
            $safeRoomName = htmlspecialchars($roomName, ENT_QUOTES, 'UTF-8');
            $html = <<<HTML
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>You've been invited to a meeting</h2>
    <p><strong>{$safeOrganizer}</strong> added the following meeting to their
    calendar and included you, based on a request noticed in the
    <strong>{$safeRoomName}</strong> Talk conversation:</p>
    <p><strong>{$safeTitle}</strong><br>{$when}</p>
    <p style="font-size: 12px; color: #999;">
        This event was NOT automatically added to your own calendar — add it
        yourself if you'd like it there.
        <br>This notification was sent automatically by Boudica AI.
    </p>
</body>
</html>
HTML;
            $message->setHtmlBody($html);
            $message->setPlainBody("{$organizerDisplayName} added \"{$title}\" ({$when}) to their calendar and included you, "
                . "based on a request noticed in the {$roomName} Talk conversation. "
                . "This was not automatically added to your own calendar.");

            $this->mailer->send($message);
            $this->logger->info('Meeting invite notification sent to ' . count($recipients) . ' recipients');
            return true;
        } catch (\Throwable $e) {
            $this->logger->error('Failed to send meeting invite notification: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Prompts a user to confirm a meeting request the background digest
     * job found — used instead of a live chat prompt because
     * DigestService runs outside any Talk conversation, so there's no
     * BotInvokeEvent to reply to. The recipient still confirms by typing
     * '@boudica yes' back in the Talk room itself (same pending-suggestion
     * row TalkBotInvokeListener checks), this email is just how they find
     * out there's something to confirm.
     */
    public function sendMeetingSuggestionPrompt(
        string $toEmail,
        string $displayName,
        string $roomName,
        string $title,
        int $startTs,
        string $quote,
        ?string $proposedBy
    ): bool {
        try {
            $message = $this->mailer->createMessage();
            $message->setFrom([$this->fromAddress => $this->fromName]);
            $message->setTo([$toEmail => $displayName]);
            $message->setSubject("Meeting request noticed in $roomName");

            $when = date('l, F j, Y \a\t g:i A', $startTs);
            $askerLabel = $proposedBy ?: 'Someone';
            $safeRoomName = htmlspecialchars($roomName, ENT_QUOTES, 'UTF-8');
            $safeTitle = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
            $safeQuote = htmlspecialchars($quote, ENT_QUOTES, 'UTF-8');
            $safeAsker = htmlspecialchars($askerLabel, ENT_QUOTES, 'UTF-8');

            $html = <<<HTML
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>Meeting request noticed</h2>
    <p>While summarizing <strong>{$safeRoomName}</strong>, Boudica noticed
    {$safeAsker} asked for a meeting:</p>
    <p><strong>{$safeTitle}</strong><br>{$when}</p>
    <blockquote style="border-left: 3px solid #ccc; margin: 10px 0; padding-left: 10px; color: #666;">
        {$safeQuote}
    </blockquote>
    <p>Reply <strong>"@boudica yes"</strong> in that Talk conversation to add it
    to your calendar and notify the other participants, or ignore this
    email to skip it.</p>
    <p style="font-size: 12px; color: #999;">
        This confirmation stays open for 24 hours.
        <br>This notification was sent automatically by Boudica AI.
    </p>
</body>
</html>
HTML;
            $message->setHtmlBody($html);
            $message->setPlainBody(
                "While summarizing {$roomName}, Boudica noticed {$askerLabel} asked for a meeting: "
                . "\"{$title}\" ({$when}).\n\n\"{$quote}\"\n\n"
                . "Reply \"@boudica yes\" in that Talk conversation to add it to your calendar and notify "
                . "the other participants, or ignore this email to skip it. This confirmation stays open for 24 hours."
            );

            $this->mailer->send($message);
            $this->logger->info("Meeting suggestion prompt sent to {$toEmail}");
            return true;
        } catch (\Throwable $e) {
            $this->logger->error('Failed to send meeting suggestion prompt: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Sets the from address and name for email notifications
     *
     * @param string $email
     * @param string $name
     */
    public function setFromAddress(string $email, string $name): void {
        $this->fromAddress = $email;
        $this->fromName = $name;
    }
}
