<?php

declare(strict_types=1);

namespace OCA\BoudicaAi\Service;

use OCP\Mail\IMailer;
use OCP\Mail\IMessage;
use Psr\Log\LoggerInterface;

class TranscriptEmailService {
    private IMailer $mailer;
    private LoggerInterface $logger;
    private string $fromAddress;
    private string $fromName;

    public function __construct(
        IMailer $mailer,
        LoggerInterface $logger
    ) {
        $this->mailer = $mailer;
        $this->logger = $logger;
        // These should come from Nextcloud config in a real implementation
        $this->fromAddress = 'boudica@myboudica.com';
        $this->fromName = 'Boudica';
    }

    /**
     * Sends call transcript to participants
     * 
     * @param array $recipients Associative array of email => display_name
     * @param string $callSummary Transcript text or AI-generated summary
     * @param string $roomName The Talk room name
     * @param int $callStartTime Unix timestamp of call start
     * @return bool Success status
     */
    public function sendTranscriptEmail(array $recipients, string $callSummary, string $roomName, int $callStartTime): bool {
        if (empty($recipients)) {
            $this->logger->warning('No recipients to send transcript email');
            return false;
        }

        try {
            $message = $this->mailer->createMessage();
            $message->setFrom([$this->fromAddress => $this->fromName]);
            
            // Build the full recipient list first, then set it once — setTo()
            // REPLACES the whole recipient list on each call, it doesn't add to it.
            // Calling it inside a loop (as before) meant only the last recipient in
            // $recipients actually ended up on the outgoing message; everyone before
            // them was silently overwritten and never received the email.
            $toList = [];
            foreach ($recipients as $email => $displayName) {
                $toList[$email] = $displayName;
            }
            $message->setTo($toList);

            $message->setSubject("Call Transcript: $roomName - " . date('Y-m-d H:i', $callStartTime));

            // Build HTML email
            $callDate = date('l, F j, Y \a\t g:i A', $callStartTime);
            $html = <<<HTML
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>Call Transcript</h2>
    <p><strong>Room:</strong> $roomName</p>
    <p><strong>Date & Time:</strong> $callDate</p>
    <p><strong>Participants:</strong> {COUNT}</p>
    
    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    
    <h3>Transcript</h3>
    <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; white-space: pre-wrap;">
        {TRANSCRIPT}
    </div>
    
    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    
    <p style="font-size: 12px; color: #999;">
        This transcript was automatically generated by Boudica AI.
        <br>Nextcloud Instance: boudi.ca
    </p>
</body>
</html>
HTML;

            $html = str_replace('{COUNT}', (string) count($recipients), $html);
            $html = str_replace('{TRANSCRIPT}', htmlspecialchars($callSummary, ENT_QUOTES, 'UTF-8'), $html);

            $message->setHtmlBody($html);

            // Also set plain text fallback
            $plainText = "Call Transcript\n\n";
            $plainText .= "Room: $roomName\n";
            $plainText .= "Date & Time: $callDate\n";
            $plainText .= "Participants: " . count($recipients) . "\n\n";
            $plainText .= "Transcript:\n";
            $plainText .= $callSummary;

            $message->setPlainBody($plainText);

            $this->mailer->send($message);

            $this->logger->info('Transcript email sent to ' . count($recipients) . ' recipients');
            return true;

        } catch (\Throwable $e) {
            $this->logger->error('Failed to send transcript email: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Sets the from address and name for email notifications
     * 
     * @param string $email
     * @param string $name
     */
    public function setFromAddress(string $email, string $name): void {
        $this->fromAddress = $email;
        $this->fromName = $name;
    }
}
